apiVersion: v1
kind: Service
metadata:
  name: fleetmap-webapp
spec:
  selector:
    app: webapp
  type: LoadBalancer # -> the recommended way to expose a service on the internet
  ports:
  - name: http
    port: 80

--- 
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: "fleetman-queue"
  type: ClusterIP
  ports:
  - name: http
    port: 8161
  - name: endpoint
    port: 61616
--- 
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: "position-tracker"
  type: ClusterIP # only expose to other pods in the cluster
  ports:
  - name: http
    port: 8080
--- 
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    app: "api-gateway"
  type: ClusterIP # only expose to other pods in the cluster
  ports:
  - name: http
    port: 8080
